/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poly.sv.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Utech
 */
public class MainForm extends javax.swing.JFrame {
    private StudentManagementPanel mStudentPanel;
    private GPAManagementPanel mGPAPanel;
    /**
     * Creates new form MainFrom
     */
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        tplError = new javax.swing.JPanel();
        tplMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        error = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuManageStd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuManageGPA = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout tplErrorLayout = new javax.swing.GroupLayout(tplError);
        tplError.setLayout(tplErrorLayout);
        tplErrorLayout.setHorizontalGroup(
            tplErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tplErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        tplErrorLayout.setVerticalGroup(
            tplErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tplErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );

        error.setText("Hệ thống");
        error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorActionPerformed(evt);
            }
        });

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/sv/icons/logout-icon-32.png"))); // NOI18N
        menuExit.setText("Thoát");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        error.add(menuExit);

        jMenuBar1.add(error);

        jMenu1.setText("Quản lý");

        menuManageStd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageStd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/sv/icons/10207-man-student-light-skin-tone-icon-24.png"))); // NOI18N
        menuManageStd.setText("Quản lý sinh viên");
        menuManageStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageStdActionPerformed(evt);
            }
        });
        jMenu1.add(menuManageStd);
        jMenu1.add(jSeparator1);

        menuManageGPA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageGPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/sv/icons/gpa-icon-24.png"))); // NOI18N
        menuManageGPA.setText("Quản lý điểm");
        menuManageGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageGPAActionPerformed(evt);
            }
        });
        jMenu1.add(menuManageGPA);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorActionPerformed
        
    }//GEN-LAST:event_errorActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuManageStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageStdActionPerformed
        if(mStudentPanel == null) {
        mStudentPanel = new StudentManagementPanel();
        ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/poly/sv/icons/10207-man-student-light-skin-tone-icon-16.png"));
        tplMainBoard.addTab("Quản Lý Sinh Viên", icon, mStudentPanel, "Quản lý sinh viên");
        }
        tplMainBoard.setSelectedComponent(mStudentPanel);
                
    }//GEN-LAST:event_menuManageStdActionPerformed

    private void menuManageGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageGPAActionPerformed
        if(mGPAPanel == null) {
            mGPAPanel = new GPAManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/poly/sv/icons/Actions-edit-delete-icon-16.png"));
        tplMainBoard.addTab("Quản Lý Điểm", icon, mGPAPanel, "Quản lý điểm");
        }
        tplMainBoard.setSelectedComponent(mGPAPanel);
    }//GEN-LAST:event_menuManageGPAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu error;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuManageGPA;
    private javax.swing.JMenuItem menuManageStd;
    private javax.swing.JPanel tplError;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
